language: ruby
rvm:
- 2.6.1
- ruby-head
gemfile: "gems.rb"
addons:
  postgresql: "9.6"
before_script:
- "ruby lib/initial_setup.rb ../.travis_setup"
- "psql -c 'create database balance_test;' -U postgres"
- "rails db:migrate"
matrix:
  allow_failures:
  - rvm: ruby-head
