language: ruby
rvm:
  - 1.9.3
  - 2.0.0
before_script:
  - "ruby lib/initial_setup.rb ../.travis_setup"
  - "mysql -e 'create database balance_test;'"
  - "bundle exec rake db:migrate"
matrix:
  allow_failures:
    - rvm: 2.0.0
