sudo: false
language: ruby
rvm:
  - 2.4.3
  - 2.5.0
  - ruby-head
gemfile: "gems.rb"
before_script:
  - "ruby lib/initial_setup.rb ../.travis_setup"
  - "psql -c 'create database balance_test;' -U postgres"
  - "rails db:migrate"
matrix:
  allow_failures:
    - rvm: ruby-head
