sudo: false
language: ruby
rvm:
  - 2.3.3
  - 2.4.0
before_script:
  - "ruby lib/initial_setup.rb ../.travis_setup"
  - "psql -c 'create database balance_test;' -U postgres"
  - "bundle exec rake db:migrate"
